#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/hulu-salt-syndic" ]; then
	if [ ! -e "/etc/init/hulu-salt-syndic.conf" ]; then
		update-rc.d hulu-salt-syndic defaults >/dev/null
	fi
	invoke-rc.d hulu-salt-syndic start || exit $?
fi
# End automatically added section
# Automatically added by dh_installinit
update-rc.d -f hulu-salt-syndic remove >/dev/null || exit $?
# End automatically added section
