#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = install ] || [ "$1" = upgrade ]; then
	if [ -e "/etc/init.d/hulu-salt-minion" ] && [ ! -L "/etc/init.d/hulu-salt-minion" ]; then
		if [ "`md5sum \"/etc/init.d/hulu-salt-minion\" | sed -e \"s/ .*//\"`" != \
		     "`dpkg-query -W -f='${Conffiles}' hulu-salt-minion | sed -n -e \"\\\\' /etc/init.d/hulu-salt-minion '{s/ obsolete$//;s/.* //p}\"`" ]
		then
			echo "Obsolete conffile /etc/init.d/hulu-salt-minion has been modified by you, renaming to .dpkg-bak"
			mv -f "/etc/init.d/hulu-salt-minion" "/etc/init.d/hulu-salt-minion.dpkg-bak"
		else
			rm -f "/etc/init.d/hulu-salt-minion"
		fi
	fi
fi
# End automatically added section
